name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Build and Deploy
      uses: appleboy/ssh-action@v0.1.8
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      with:
        host: ${{ secrets.EC2_HOST }}
        username: runner
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        envs: REACT_APP_API_URL
        script: |
          cd ${{ secrets.APP_PATH }}
          git pull origin main
          echo "Building with REACT_APP_API_URL=${REACT_APP_API_URL}"
          docker build \
            --build-arg REACT_APP_API_URL="${REACT_APP_API_URL}" \
            -f Dockerfile \
            -t annotation-app:latest .
          docker stop annotation-app || true
          docker rm annotation-app || true
          docker run -d \
            --name annotation-app \
            -p 9898:80 \
            annotation-app:latest

    - name: Cleanup old images
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: runner
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        script: |
          docker system prune -f
